COUNTRIES = [
    {"name": "Afghanistan", "currency": "AFN"}, {"name": "Albania", "currency": "ALL"},
    {"name": "Algeria", "currency": "DZD"}, {"name": "Angola", "currency": "AOA"},
    {"name": "Argentina", "currency": "ARS"}, {"name": "Armenia", "currency": "AMD"},
    {"name": "Australia", "currency": "AUD"}, {"name": "Azerbaijan", "currency": "AZN"},
    {"name": "Bahrain", "currency": "BHD"}, {"name": "Bangladesh", "currency": "BDT"},
    {"name": "Belarus", "currency": "BYN"}, {"name": "Benin", "currency": "XOF"},
    {"name": "Bhutan", "currency": "BTN"}, {"name": "Bolivia", "currency": "BOB"},
    {"name": "Bosnia and Herzegovina", "currency": "BAM"}, {"name": "Botswana", "currency": "BWP"},
    {"name": "Brazil", "currency": "BRL"}, {"name": "Burkina Faso", "currency": "XOF"},
    {"name": "Burundi", "currency": "BIF"}, {"name": "Cambodia", "currency": "KHR"},
    {"name": "Cameroon", "currency": "XAF"}, {"name": "Central African Republic", "currency": "XAF"},
    {"name": "Chad", "currency": "XAF"}, {"name": "Chile", "currency": "CLP"},
    {"name": "China", "currency": "CNY"}, {"name": "Colombia", "currency": "COP"},
    {"name": "Comoros", "currency": "KMF"}, {"name": "Congo, Dem. Rep.", "currency": "CDF"},
    {"name": "Congo, Rep.", "currency": "XAF"}, {"name": "Costa Rica", "currency": "CRC"},
    {"name": "Cote d'Ivoire", "currency": "XOF"}, {"name": "Cuba", "currency": "CUP"},
    {"name": "Dominican Republic", "currency": "DOP"}, {"name": "Ecuador", "currency": "USD"},
    {"name": "Egypt", "currency": "EGP"}, {"name": "El Salvador", "currency": "USD"},
    {"name": "Eritrea", "currency": "ERN"}, {"name": "Eswatini", "currency": "SZL"},
    {"name": "Ethiopia", "currency": "ETB"}, {"name": "Fiji", "currency": "FJD"},
    {"name": "Gabon", "currency": "XAF"}, {"name": "Gambia", "currency": "GMD"},
    {"name": "Georgia", "currency": "GEL"}, {"name": "Ghana", "currency": "GHS"},
    {"name": "Guatemala", "currency": "GTQ"}, {"name": "Guinea", "currency": "GNF"},
    {"name": "Guinea-Bissau", "currency": "XOF"}, {"name": "Guyana", "currency": "GYD"},
    {"name": "Haiti", "currency": "HTG"}, {"name": "Honduras", "currency": "HNL"},
    {"name": "India", "currency": "INR"}, {"name": "Indonesia", "currency": "IDR"},
    {"name": "Iran", "currency": "IRR"}, {"name": "Iraq", "currency": "IQD"},
    {"name": "Jamaica", "currency": "JMD"}, {"name": "Jordan", "currency": "JOD"},
    {"name": "Kazakhstan", "currency": "KZT"}, {"name": "Kenya", "currency": "KES"},
    {"name": "Kiribati", "currency": "AUD"}, {"name": "Korea, Rep.", "currency": "KRW"},
    {"name": "Kosovo", "currency": "EUR"}, {"name": "Kyrgyz Republic", "currency": "KGS"},
    {"name": "Lao PDR", "currency": "LAK"}, {"name": "Lebanon", "currency": "LBP"},
    {"name": "Lesotho", "currency": "LSL"}, {"name": "Liberia", "currency": "LRD"},
    {"name": "Libya", "currency": "LYD"}, {"name": "Madagascar", "currency": "MGA"},
    {"name": "Malawi", "currency": "MWK"}, {"name": "Malaysia", "currency": "MYR"},
    {"name": "Maldives", "currency": "MVR"}, {"name": "Mali", "currency": "XOF"},
    {"name": "Mauritania", "currency": "MRU"}, {"name": "Mauritius", "currency": "MUR"},
    {"name": "Mexico", "currency": "MXN"}, {"name": "Moldova", "currency": "MDL"},
    {"name": "Mongolia", "currency": "MNT"}, {"name": "Montenegro", "currency": "EUR"},
    {"name": "Morocco", "currency": "MAD"}, {"name": "Mozambique", "currency": "MZN"},
    {"name": "Myanmar", "currency": "MMK"}, {"name": "Namibia", "currency": "NAD"},
    {"name": "Nepal", "currency": "NPR"}, {"name": "Nicaragua", "currency": "NIO"},
    {"name": "Niger", "currency": "XOF"}, {"name": "Nigeria", "currency": "NGN"},
    {"name": "North Macedonia", "currency": "MKD"}, {"name": "Pakistan", "currency": "PKR"},
    {"name": "Panama", "currency": "PAB"}, {"name": "Papua New Guinea", "currency": "PGK"},
    {"name": "Paraguay", "currency": "PYG"}, {"name": "Peru", "currency": "PEN"},
    {"name": "Philippines", "currency": "PHP"}, {"name": "Rwanda", "currency": "RWF"},
    {"name": "Samoa", "currency": "WST"}, {"name": "Sao Tome and Principe", "currency": "STN"},
    {"name": "Senegal", "currency": "XOF"}, {"name": "Serbia", "currency": "RSD"},
    {"name": "Sierra Leone", "currency": "SLE"}, {"name": "Solomon Islands", "currency": "SBD"},
    {"name": "Somalia", "currency": "SOS"}, {"name": "South Africa", "currency": "ZAR"},
    {"name": "South Sudan", "currency": "SSP"}, {"name": "Sri Lanka", "currency": "LKR"},
    {"name": "Sudan", "currency": "SDG"}, {"name": "Suriname", "currency": "SRD"},
    {"name": "Tajikistan", "currency": "TJS"}, {"name": "Tanzania", "currency": "TZS"},
    {"name": "Thailand", "currency": "THB"}, {"name": "Timor-Leste", "currency": "USD"},
    {"name": "Togo", "currency": "XOF"}, {"name": "Tonga", "currency": "TOP"},
    {"name": "Tunisia", "currency": "TND"}, {"name": "Turkiye", "currency": "TRY"},
    {"name": "Turkmenistan", "currency": "TMT"}, {"name": "Tuvalu", "currency": "AUD"},
    {"name": "Uganda", "currency": "UGX"}, {"name": "Ukraine", "currency": "UAH"},
    {"name": "Uruguay", "currency": "UYU"}, {"name": "Uzbekistan", "currency": "UZS"},
    {"name": "Vanuatu", "currency": "VUV"}, {"name": "Venezuela", "currency": "VES"},
    {"name": "Vietnam", "currency": "VND"}, {"name": "Yemen", "currency": "YER"},
    {"name": "Zambia", "currency": "ZMW"}, {"name": "Zimbabwe", "currency": "ZWL"},
]
